apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: awsx-cli
  labels:
    app.kubernetes.io/version: "0.2"
  annotations:
    tekton.dev/pipelines.minVersion: "0.17.0"
    tekton.dev/categories: CLI
    tekton.dev/tags: cli
    tekton.dev/displayName: "awsx"
    tekton.dev/platforms: "linux/amd64"
spec:
  description: >-
    This task performs operations on Amazon Web Services resources using aws.
  workspaces:
    - name: source
      optional: true
    - name: secrets
      optional: true
      mountPath: /tekton/home/.aws
  params:
    - name: ARGS
      description: AWSX cli arguments to be passed
      type: array
      default: ["--help"]
  steps:
    - name: awsx-cli
      image: synectiks/awsx:latest #tag: 2.0.52
      args:
        - "$(params.ARGS)"